# Generated by Django 4.1.3 on 2022-12-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_shopinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='phone_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='shop_address',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='shop_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
