# Generated by Django 4.1.3 on 2022-12-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_shopinfo_phone_number_shopinfo_shop_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='shop_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='shop_address',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
