# Generated by Django 4.1.3 on 2022-12-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_shopinfo_shop_email_alter_shopinfo_shop_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
