# Generated by Django 4.1.3 on 2022-12-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_shopinfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='shop_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
