# Generated by Django 4.1.3 on 2022-12-18 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_shopinfo_shop_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='shop_address',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2, 'The address must be a minimum of 5 chars')]),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='shop_name',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2, 'The name must be a minimum of 2 chars')]),
        ),
    ]
